---
title: "PARTNER"
author: "J. Lucas McKay"
date: "1/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
# Download demographics, intervention, outcomes data
source("DownloadAndClean.R")
```

```{r}
# All participants
all.participants = demographics.data$`Participant ID`

# Randomized participants
randomized.participants = all.participants |> setdiff(c("PRR002","PRR015","PRR019","PRR020"))
```

# Balance between Arms at Randomization

```{r}
demo.table = arsenal::tableby(Arm~.,demographics.data |> filter(`Participant ID` %in% randomized.participants) |> select(-`Participant ID`)) |>
  summary(digits=1,digits.p=2,digits.pct=0) |>
  as.data.frame() |>
  FixColumn()
demo.table |>  PrintNicely()
```

# Progress through study

```{r}
visit.dates = DownloadReport('33308') |> 
  filter(`Participant ID` %in% randomized.participants)

baseline.participants = visit.dates |> 
  filter(`Event Name` == "Baseline (Arm 3: Randomized Phase)") |> 
  filter(!is.na(`Assessment Date`)) |> 
  pull(`Participant ID`)

month.3.participants = visit.dates |> 
  filter(`Event Name` == "3-month (Arm 3: Randomized Phase)") |> 
  filter(!is.na(`Assessment Date`)) |> 
  pull(`Participant ID`)

month.7.participants = visit.dates |> 
  filter(`Event Name` == "7-8 Month Screening (Arm 3: Randomized Phase)") |> 
  filter(!is.na(`Total points for MOCA`)) |> 
  pull(`Participant ID`)

month.12.participants = visit.dates |> 
  filter(`Event Name` == "12-month (Arm 3: Randomized Phase)") |> 
  filter(!is.na(`Assessment Date`)) |> 
  pull(`Participant ID`)

intervention.visits = visit.dates |> 
  filter(`Event Name` == "Intervention (Arm 3: Randomized Phase)") |> 
  group_by(`Participant ID`) |> 
  summarize(`Visits Completed` = max(row_number()))

study.status = visit.dates |> 
  filter(`Event Name` == "Baseline (Arm 3: Randomized Phase)") |> 
  filter(!is.na(`Assessment Date`)) |> 
  mutate(`Study Month` = round(as.numeric(lubridate::today() - `Assessment Date`)/30.4,1)) |> 
  select(`Participant ID`, `Study Month`) |> 
  left_join(intervention.visits)

study.status = tibble(`Participant ID` = all.participants) |> left_join(study.status) |> 
  arrange(`Participant ID`) |> 
  mutate(Baseline = `Participant ID` %in% baseline.participants) |> 
  mutate(`Month 3` = `Participant ID` %in% month.3.participants) |> 
  mutate(`Month 7` = `Participant ID` %in% month.7.participants) |> 
  mutate(`Month 12` = `Participant ID` %in% month.12.participants)

study.status |> PrintNicely()

```

```{r}

intervention.data |> filter(`Participant ID` %in% randomized.participants) |> 
  filter(`Event Name` == "Intervention (Arm 3: Randomized Phase)") |> 
  arrange(`Participant ID`,`Date and Time`) %>%
  group_by(`Participant ID`) %>%
  mutate(`Study Day` = lubridate::as_date(`Date and Time`)) %>%
  mutate(`Study Day` = `Study Day` - min(`Study Day`)) %>% 
  mutate(`Study Day` = as.numeric(`Study Day`)) |> 
  mutate(`Training Phase` = if_else(row_number()<20,"Initial","Maintenance")) %>% 
  ungroup() %>% 
  mutate(`Participant ID` = factor(`Participant ID`)) |> 
  mutate(`PRR ID` = forcats::fct_rev(`Participant ID`)) %>% 
  ggplot(aes(`Study Day`,`PRR ID`,color = `PRR ID`,shape=`Training Phase`)) +
  geom_point()+
  theme_minimal() +
  ylab("Participant") +
  guides(color = F) +
  theme(legend.position = c(0.8, 0.125))
ggsave("attendance.svg")
```



```{r}
# link the unique identifiers from the previous table. note that there will be duplicate rows due to the way the redcap table is created.
outcomes.data = outcomes.data |> filter(participants %in% randomized.participants)
outcomes.data = outcomes.data |> filter(redcap_event_name %contains% "^Baseline|^3-month|^12|^7")

# add demographic variables
outcomes.data = outcomes.data |> left_join(demographics.data |> rename(participants = `Participant ID`) |> select(-MoCA))

baseline.instruments = c("Lawton-Brody Instrumental Activities of Daily Living Scale",
"BDI Total Score",
"PASE Total Score",
"SF12_PCS (Physical Component Summary)",
"SF12_MCS (Mental Component Summary)",
"IPA",
"ABC",
"AUA Symptom Score",
"LSQ",
"CES-D",
"MSPSS",
"PHQ-9",
"QOL-AD",
"MoCA",
"Trail A",
"Trail B",
"RAVLT Composite Score",
"reyosterrieth_complex_figure_complete",
"Brooks Spatial Memory Percent Correct",
"Benton's JLO",
"Number Span Forward",
"Number Span Backward",
"D-KEFS Inhibition/Switching",
"WRAT",
"BNT Correct",
"BNT Incorrect",
"Corsi Blocks Product Score (Trials x Span)",
"D-KEFS TOL",
"Average Forward Gait Speed",
"30 Second Chair Stand",
"FSST Best Time",
"6MWT (m)",
"TUG simple (baseline) (s)",
"Cognitive Dual Task (s)",
"Manual Dual Task (s)",
"turn_test_steps_right",
"R: Time to turn (s)",
"turn_test_steps_left",
"L: Time to turn (s)",
"Tandem Walk number of interruptions",
"Tandem Stance (L)",
"Tandem Stance (R)",
"OLS (L)",
"OLS (R)",
"Jump Distance (m)",
"foot_length_m",
"fab_scale_category",
"BPST Product",
"Mini-BESTest Total Score",
"DGI (/24)"
)

month.3.instruments = setdiff(baseline.instruments,c(
  "MoCA",
  "WRAT")
  )

month.7.instruments = c(
  "MoCA",
  "30 Second Chair Stand",
  "TUG simple (baseline) (s)",
  "Cognitive Dual Task (s)",
  "Manual Dual Task (s)",
  "calc_score"
)

baseline.outcomes = outcomes.data |>
  filter(redcap_event_name == "Baseline (Arm 3: Randomized Phase)") |>
  select(participants,any_of(baseline.instruments)) |>
  filter(participants %in% baseline.participants)
month.3.outcomes = outcomes.data |>
  filter(redcap_event_name == "3-month (Arm 3: Randomized Phase)") |>
  select(participants,any_of(month.3.instruments)) |>
  filter(participants %in% month.3.participants)
month.7.outcomes = outcomes.data |>
  filter(redcap_event_name == "7-8 Month Screening (Arm 3: Randomized Phase)") |>
  select(participants,any_of(month.7.instruments)) |>
  filter(participants %in% month.7.participants)


```



# Summary of Completed Instruments


```{r}
CountCompleted = function(d = baseline.outcomes){
  df = d |> select(-participants) |> as.data.frame()
  n.instruments = ncol(df)
  # return a character vector like 48/49, etc
  n.completed = rowSums(!is.na(df)==T)
  fractions = rowSums(!is.na(df)==T) |> as.character() |> paste0("/",n.instruments)
  # add an asterisk to missing datapoints
  fractions[n.completed<n.instruments] = paste0(fractions[n.completed<n.instruments],"*")
  fractions
}

AddCompleted = function(d = baseline.outcomes){
  d$completed = CountCompleted(d)  
  d
}

baseline.outcomes = baseline.outcomes |> AddCompleted()
month.3.outcomes = month.3.outcomes |> AddCompleted()
month.7.outcomes = month.7.outcomes |> AddCompleted()

# create a summary table
completed.instruments = baseline.outcomes |>
  select(participants, completed) |>
  rename(Baseline = completed) |> 
  left_join(
    month.3.outcomes |> select(participants, completed) |> rename(`Month 3` = completed)
    ) |> 
  left_join(
    month.7.outcomes |> select(participants, completed) |> rename(`Month 7/8` = completed)
    ) |> 
  rename(ID = participants)

completed.instruments |> PrintNicely()
```

# Item scores

```{r}
baseline.outcomes |> write_csv("baseline.csv",na="")
month.3.outcomes |> write_csv("month.3.csv",na="")
month.7.outcomes |> write_csv("month.7.csv",na="")
```

[Baseline](./baseline.csv)

[3 Month](./month.3.csv)

[7/8 Month](./month.7.csv)





